
name: Terraform GKE Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-sa-key.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Write GCP credentials to file
        run: echo '${{ secrets.GCP_SA_KEY }}' | base64 -d > gcp-sa-key.json

      - name: Terraform Init with GCS Backend
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -var="gcp_sa_key_path=gcp-sa-key.json" -out=tfplan

      - name: Upload Plan File
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    environment:
      name: Production   # Must match the environment you created
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Decode and write GCP credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > gcp-sa-key.json

      - name: Download Plan File
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Init
        run: terraform init -reconfigure
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-sa-key.json

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
