
name: Terraform GKE Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-sa-key.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Write GCP credentials to file
        run: echo '${{ secrets.GCP_SA_KEY }}' | base64 -d > gcp-sa-key.json

      - name: Terraform Init with GCS Backend
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -var="gcp_sa_key_path=gcp-sa-key.json"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var="gcp_sa_key_path=gcp-sa-key.json"
